name: Build and deploy backend

on:
  push:
    branches:
      - main
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv env
          .\env\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip backend code
        run: powershell -command "Compress-Archive -Path * -DestinationPath ../backend.zip -Force"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend.zip
          path: backend.zip

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend.zip
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: freelancerhub-api-edubw3ephznye
          slot-name: Production
          package: backend.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
