# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - freelancehub-api-edubw3ephznye(Production), Build and deploy Python app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m venv env
        .\env\Scripts\activate
        pip install -r requirements.txt

    - name: Zip the application files
      run: Compress-Archive .\* app.zip

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: freelancehub-api-edubw3ephznye
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FD02612BBA27499A924C3834FB694F4E }}
        package: '.\app.zip'

